//
//  MySymbols.swift
//  Grocy-SwiftUI
//
//  Created by Georg Meissner on 09.02.21.
//

import Foundation

struct MySymbols {
    static let purchase = "cart"
    static let consume = "fork.knife"
    static let open = "envelope.open"
    static let transfer = "arrow.left.arrow.right"
    static let inventory = "list.bullet"
    static let stockJournal = "list.bullet.rectangle"
    static let addToShoppingList = "note.text.badge.plus"
    static let shoppingList = "cart.fill"
    static let masterData = "folder"
    static let settings = "gear"
    static let chores = "house"
    static let batteries = "battery.25percent"
    static let tasks = "point.fill.topleft.down.curvedto.point.fill.bottomright.up"

    static let stockOverview = "archivebox"
    static let product = "tag"
    static let quantityUnit = "scalemass"
    static let location = "location"
    static let store = "house"
    static let productGroup = "square.on.circle"
    static let recipe = "book"
    static let picture = "photo"
    static let gallery = "photo.on.rectangle.angled"
    static let user = "person"

    static let amount = "number.circle"
    static let price = "banknote"
    static let spoiled = "trash.circle"
    static let doesntSpoil = "trash.slash.circle"
    static let description = "text.justifyleft"
    static let date = "calendar"
    static let energy = "flame"
    static let freezing = "thermometer.snowflake"
    static let thawing = "thermometer.sun"
    static let accumulate = "arrow.triangle.merge"
    static let tareWeight = "scalemass.fill"
    static let selfProduction = "house"
    static let name = "tag"

    static let logFile = "doc.plaintext"
    static let info = "info.circle"
    static let offline = "wifi.slash"
    static let api = "chevron.left.forwardslash.chevron.right"
    static let unknown = "questionmark"
    static let timeout = "clock.arrow.circlepath"
    static let decimalPlaces = "00.square"
    static let hint = "questionmark.circle.fill"
    static let language = "flag"

    static let new = "plus"
    static let edit = "square.and.pencil"
    static let delete = "trash"
    static let success = "checkmark"
    static let failure = "xmark"
    static let share = "square.and.arrow.up"
    static let cancel = "xmark.circle.fill"
    static let upload = "square.and.arrow.up.fill"
    static let save = "checkmark"
    static let logout = "rectangle.portrait.and.arrow.right"
    static let reset = "arrow.counterclockwise"

    static let filter = "line.3.horizontal.decrease.circle"
    static let reload = "arrow.triangle.2.circlepath"
    static let search = "magnifyingglass"
    static let menuPick = "chevron.down.circle"
    static let done = "checkmark.circle"
    static let clear = "clear"
    static let undo = "arrow.counterclockwise"
    static let timedRefresh = "clock.arrow.2.circlepath"
    static let sort = "arrow.up.arrow.down.square"
    static let sortForward = "arrow.up"
    static let sortReverse = "arrow.down"
    static let groupBy = "square.grid.2x2"
    static let sortCategory = "line.3.horizontal.decrease.circle"
    static let sortOrder = "arrow.up.arrow.down"
    static let active = "checkmark.circle.fill"
    static let warning = "exclamationmark.triangle.fill"
    static let error = "xmark.circle.fill"
    static let notSaved = "square.and.arrow.down.badge.clock"

    static let qrScan = "qrcode.viewfinder"
    static let barcodeScan = "barcode.viewfinder"
    static let barcode = "barcode"
    static let camera = "camera"
    static let changeCamera = "arrow.triangle.2.circlepath.camera"
    static let app = "app"
    static let devMode = "wrench.and.screwdriver"
    
    static let expiringSoon = "hourglass.bottomhalf.fill"
    static let overdue = "exclamationmark.triangle.fill"
    static let expired = "trash.fill"
    static let belowMinStock = "chart.bar.fill"
}
